#ifndef SRC_MODEL_CONSTANTS_H_
#define SRC_MODEL_CONSTANTS_H_

typedef float Real;

#define STATION_COUNT 5
#define LANE_COUNT 4
#define BOGIE_SWITCH_COUNT 50000000
#define ROCK_AMOUNT 500000000

#endif /* SRC_MODEL_CONSTANTS_H_ */
